### ISSUE TITLE
06/18/2020 Review

### ISSUE THREAD

**Issue by Victorgonbu** [mimipeshy/conference-page#2]
Hi Peris, Great job! so far you have accomplished a really good looking page. Here are some things to keep in mind so your project will look even more flawless:

- Remember to adjust section images for a small screen and adjust or change the footer logo, it's not visible the way yo have it.

- Maybe if you have time, it would be wonderful if you add some life to your page.

Wish you the best!

**Comment by mimipeshy** [comment]
hahaha thanks!
